#!/bin/sh

set -ex

if [ "x$CIP_ENV" == "x" ]; then
  echo "please set CIP_ENV to one of:"
  echo " export CIP_ENV=ALIEN_INSTALL_TYPE=share"
  echo " export CIP_ENV=ALIEN_INSTALL_TYPE=system"
  false
fi

if echo $CIP_ENV | grep -q system; then
  echo use system rust
  cip pkg rust
else
  echo use internet expat
fi
